pretrained_model_name_or_path = "./models/SDXLModel.safetensors"
sample_prompts = "OUTPUT/DATASET_NAME/sample_prompts.txt"
output_dir = "CHANGE"
output_name = "CHANGE"
train_data_dir = "CHANGE"
logging_dir = "CHANGE"


adaptive_noise_scale = 0
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
clip_skip = 1
dynamo_backend = "no"
max_train_epochs = 1
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
ip_noise_gamma = 0.1
keep_tokens = 0
learning_rate = 8e-6
learning_rate_te1 = 3e-6
learning_rate_te2 = 0
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
min_bucket_reso = 256
mixed_precision = "bf16"
multires_noise_discount = 0
multires_noise_iterations = 0
noise_offset = 0.0357
noise_offset_type = "Original"
optimizer_args = [
  "scale_parameter=False",
  "relative_step=False",
  "warmup_init=False",
  "weight_decay=0.01",
]
optimizer_type = "Adafactor"
persistent_data_loader_workers = 0
prior_loss_weight = 1
resolution = "1024,1280"
sample_every_n_steps = 250
caption_extension = ".txt"
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
train_batch_size = 1
train_text_encoder = true
vae = "stabilityai/sdxl-vae"
vae_batch_size = 2
wandb_run_name = "X"
