apiVersion: v1
kind: Secret
metadata:
  name: autotrainx-secrets
  namespace: autotrainx
  labels:
    app.kubernetes.io/name: autotrainx
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # These should be base64 encoded in production
  # Use kubectl create secret or external secret management
  SECRET_KEY: "your-very-secure-secret-key-change-in-production"
  DATABASE_URL: "sqlite:///app/DB/executions.db"
  JWT_SECRET_KEY: "your-jwt-secret-key"
  
  # Google Sheets credentials (if used)
  GOOGLE_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "your-project",
      "private_key_id": "key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
      "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: autotrainx
  labels:
    app.kubernetes.io/name: autotrainx
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials for pulling private images
  # Create with: kubectl create secret docker-registry registry-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=your-username \
  #   --docker-password=your-token \
  #   --namespace=autotrainx
  .dockerconfigjson: eyYOUR_BASE64_ENCODED_CONFIG_HERE