# Alertmanager configuration for AutoTrainX
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@autotrainx.com'
  smtp_auth_username: 'alerts@autotrainx.com'
  smtp_auth_password: 'your-smtp-password'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    # Critical alerts go to on-call immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m

    # API-specific alerts
    - match:
        service: autotrainx-api
      receiver: 'api-team'
      
    # Training-specific alerts
    - match:
        service: autotrainx-training
      receiver: 'training-team'
      
    # Infrastructure alerts
    - match:
        service: infrastructure
      receiver: 'infrastructure-team'

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit API health alerts if API is down
  - source_match:
      alertname: 'AutoTrainXAPIDown'
    target_match_re:
      alertname: 'AutoTrainXAPI.*'
    equal: ['instance']

# Receiver configurations
receivers:
  - name: 'default'
    email_configs:
      - to: 'alerts@autotrainx.com'
        subject: '[AutoTrainX] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          
          Details:
          {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}
          {{ end }}
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@autotrainx.com'
        subject: '[AutoTrainX CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
        channel: '#autotrainx-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          
          {{ .Annotations.description }}
          
          • Service: {{ .Labels.service }}
          • Instance: {{ .Labels.instance }}
          • Started: {{ .StartsAt.Format "15:04:05" }}
          {{ if .Annotations.runbook_url }}
          • <{{ .Annotations.runbook_url }}|Runbook>
          {{ end }}
          {{ end }}
        color: 'danger'
        send_resolved: true

  - name: 'api-team'
    email_configs:
      - to: 'api-team@autotrainx.com'
        subject: '[AutoTrainX API] {{ .GroupLabels.alertname }}'
        body: |
          API Alert: {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
        channel: '#autotrainx-api'
        title: 'API Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'training-team'
    email_configs:
      - to: 'training-team@autotrainx.com'
        subject: '[AutoTrainX Training] {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
        channel: '#autotrainx-training'
        title: 'Training Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'

  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@autotrainx.com'
        subject: '[AutoTrainX Infrastructure] {{ .GroupLabels.alertname }}'
    
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'

# Templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'