apiVersion: apps/v1
kind: Deployment
metadata:
  name: autotrainx-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: API_WORKERS
          value: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1