pretrained_model_name_or_path = "./models/flux1-dev-fp8.safetensors"
ae = "./models/ae.safetensors"
clip_l = "./models/clip_l.safetensors"
t5xxl = "./models/t5xxl_fp8_e4m3fn.safetensors"
sample_prompts = "OUTPUT/DATASET_NAME/sample_prompts.txt"
output_dir = "CHANGE"
output_name = "CHANGE"
train_data_dir = "CHANGE"
logging_dir = "CHANGE"


bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
discrete_flow_shift = 3.1582
dynamo_backend = "no"
max_train_epochs = 1
fp8_base = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
highvram = true
huber_c = 0.1
huber_schedule = "snr"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 128
network_args = [
  "train_double_block_indices=all",
  "train_single_block_indices=all",
]
network_dim = 128
network_module = "networks.lora_flux"
noise_offset_type = "Original"
optimizer_args = [
  "scale_parameter=False",
  "relative_step=False",
  "warmup_init=False",
  "weight_decay=0.01",
]
optimizer_type = "Adafactor"
prior_loss_weight = 1
resolution = "1024,1280"
sample_every_n_steps = 250
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "float"
seed = 1
t5xxl_max_token_length = 512
text_encoder_lr = [5e-5, 5e-5]
timestep_sampling = "sigmoid"
train_batch_size = 1
unet_lr = 5e-5
vae_batch_size = 4
wandb_run_name = "X"
xformers = true 