apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: autotrainx-production
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: autotrainx-production

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production
  app.kubernetes.io/instance: production

images:
- name: autotrainx-api
  newTag: v1.0.0

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml

configMapGenerator:
- name: autotrainx-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
  - API_WORKERS=4
  - MAX_CONCURRENT_JOBS=3

secretGenerator:
- name: autotrainx-secrets
  behavior: merge
  literals:
  - DATABASE_URL=postgresql://autotrainx:password@postgres-service:5432/autotrainx_prod