# Promtail configuration for log collection
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # AutoTrainX API logs
  - job_name: autotrainx-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: autotrainx-api
          service: api
          __path__: /var/log/autotrainx/api*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3})\s+(?P<level>\w+)\s+(?P<logger>\S+)\s+(?P<message>.*)'
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'

  # Training logs
  - job_name: autotrainx-training
    static_configs:
      - targets:
          - localhost
        labels:
          job: autotrainx-training
          service: training
          __path__: /var/log/autotrainx/**/train_*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s+(?P<level>\w+)\s+(?P<job_id>\w+)\s+(?P<message>.*)'
      - labels:
          level:
          job_id:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'

  # Pipeline logs
  - job_name: autotrainx-pipeline
    static_configs:
      - targets:
          - localhost
        labels:
          job: autotrainx-pipeline
          service: pipeline
          __path__: /var/log/autotrainx/pipeline*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s+(?P<level>\w+)\s+(?P<module>\S+)\s+(?P<message>.*)'
      - labels:
          level:
          module:

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          service: system
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s(?P<hostname>\S+)\s(?P<service>\w+)(\[(?P<pid>\d+)\])?:\s(?P<message>.*)'
      - labels:
          hostname:
          service:
          pid:
      - timestamp:
          source: timestamp
          format: 'Jan 2 15:04:05'

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          service: nginx
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+)\s-\s(?P<remote_user>\S+)\s\[(?P<time_local>[^\]]+)\]\s"(?P<method>\w+)\s(?P<request_uri>\S+)\s(?P<server_protocol>\S+)"\s(?P<status>\d+)\s(?P<body_bytes_sent>\d+)\s"(?P<http_referer>[^"]*)"\s"(?P<http_user_agent>[^"]*)"'
      - labels:
          method:
          status:
          remote_addr:
      - timestamp:
          source: time_local
          format: '02/Jan/2006:15:04:05 -0700'

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          service: nginx
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2}\s\d{2}:\d{2}:\d{2})\s\[(?P<level>\w+)\]\s(?P<message>.*)'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006/01/02 15:04:05'