pretrained_model_name_or_path = "./models/flux1-dev-fp8.safetensors"
ae = "./models/ae.safetensors"
clip_l = "./models/clip_l.safetensors"
t5xxl = "./models/t5xxl_fp8_e4m3fn.safetensors"
sample_prompts = "OUTPUT/DATASET_NAME/sample_prompts.txt"
output_dir = "CHANGE"
output_name = "CHANGE"
train_data_dir = "CHANGE"
logging_dir = "CHANGE"


adaptive_noise_scale = 0
blocks_to_swap = 9
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
caption_extension = ".txt"
discrete_flow_shift = 3.1582
double_blocks_to_swap = 0
dynamo_backend = "no"
max_train_epochs = 1
full_bf16 = true
fused_backward_pass = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1
huber_c = 0.1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 4e-6
learning_rate_te = 0
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
multires_noise_discount = 0.3
multires_noise_iterations = 0
noise_offset = 0
noise_offset_type = "Original"
optimizer_args = [
  "scale_parameter=False",
  "relative_step=False",
  "warmup_init=False",
  "weight_decay=0.01",
]
optimizer_type = "Adafactor"
persistent_data_loader_workers = 0
prior_loss_weight = 1
resolution = "1024,1024"
sample_every_n_steps = 250
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "fp16"
seed = 1
single_blocks_to_swap = 0
t5xxl_max_token_length = 512
timestep_sampling = "sigmoid"
train_batch_size = 1
train_blocks = "all"
vae_batch_size = 4
wandb_run_name = "X"
xformers = true 