apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
      queryTimeout: "300s"
      customQueryParameters: ""
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQuerying: true
      incrementalQueryOverlapWindow: "10m"
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      timeInterval: "30s"
      maxLines: 1000
      derivedFields:
        - datasourceUid: "prometheus"
          matcherRegex: "job_id=([^\\s]+)"
          name: "Job Metrics"
          url: "/d/autotrainx-jobs/autotrainx-training-jobs?var-job_id=${__value.raw}"

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: "prometheus"